org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

mod_id=autoftbq_agent
mod_name=AutoFTBQ Agent
mod_version=0.1.0-alpha.15
mod_group=dev.autoftbq.agent

minecraft_version=1.20.1
forge_version=47.2.19
architectury_version=9.1.12
ftb_library_version=2001.2.9
ftb_teams_version=2001.3.0
ftb_quests_version=2001.4.22
